name: Lint

on: [pull_request]

jobs:
    build:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - uses: pnpm/action-setup@v3
              with:
                  version: 10

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: 'pnpm'

            - name: Install packages
              run: pnpm install

            - name: Lint
              run: pnpm lint